fix regulator_register
the error:

../drivers/regulator/cros_ec-tps65090.c:210:29: error: too few arguments to function 'regulator_register'
  210 |                 reg->rdev = regulator_register(&reg->desc, &config);
      |                             ^~~~~~~~~~~~~~~~~~

it now requires "struct device *dev"
see https://github.com/torvalds/linux/blob/5ad3cb0ed525b80c7f66c32b49a68c1f3510bec9/include/linux/regulator/driver.h#L686